## Fichero de configuración para Ariasport durante testing
# Estos valores sobreescribirán a los valores que hay en el fichero application.yml

spring.dataSource.url: jdbc:mysql://localhost:3306/ariasport_test
spring.dataSource.username: ariasport
spring.dataSource.password: secret
spring.jpa.properties.javax.persistence.schema-generation.database.action: drop-and-create

spring.cache.type: NONE

