# Configuración para la base de datos MySQL
spring.dataSource.url: jdbc:mysql://localhost:3306/ariasport
spring.dataSource.username: ariasport
spring.dataSource.password: secret

spring.jpa.hibernate.ddl-auto: create
# spring.jpa.open-in-view: false

server.port: 8084